apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-backend
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one # Kill exactly one pod matching the selector
  duration: '10m' # Duration of the active chaos window
  scheduler:
    cron: '*/30 * * * * *' # Trigger every 30 seconds
  selector:
    namespaces:
      - chaos-testing
    labelSelectors:
      app: 'backend-app'
