apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-kill-backend
  namespace: chaos-testing
spec:
  schedule: '@every 30s' # Triggers the pod-kill experiment every 30 seconds
  historyLimit: 2
  concurrencyPolicy: 'Forbid'
  type: 'PodChaos'
  podChaos:
    action: pod-kill
    mode: one # Kill exactly one pod
    selector:
      namespaces:
        - chaos-testing
      labelSelectors:
        app: 'backend-app'
