apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app
  namespace: default
  labels:
    app: sample-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-web-app
  template:
    metadata:
      labels:
        app: sample-web-app
    spec:
      containers:
      - name: web-container
        # Pulls nginx by default; in CI/CD this gets updated with the Amazon ECR repository image
        image: 927656030461.dkr.ecr.us-east-1.amazonaws.com/project6-sample-web-app:2dbbf0c3988f326e4d45db56f261187b940c8ad6
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
