apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://13.223.174.10:6443
  name: default
contexts:
- context:
    cluster: default
    insecure-skip-tls-verify: true
    user: default
  name: default
current-context: default
kind: Config
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJVjB5R1ZFVUhySDh3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemcxTnpZNE1qSXlNQjRYRFRJMk1EZ3dNekV6TkRNME1sb1hEVEkzTURndwpNekV6TkRNME1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJBdkoxdTlMSnI0SzFWQm0KQjE0cEVDcFBKbkZsbGYySENOYUlMWmVtVnl0T1NLM252U01Gd0F5cHM3UjZmajVtQW9aVzRTNDFPYVlJYkwwRApTNlVkTjhtalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUVdlTkIxZXh0OWc1STRzYTNKZjRtZmlTT0hwVEFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCOFNVMVBqOEp2NUhpRk13aEMwSzJLTCtRQUZJV3pHZXA5anYxeWpjVnVqZ0lnSnZVMjRLRHRKVUZ0TlR2aQoyZFNJQ1dCek5EQUNQVnBYTzRScElYUnFRK289Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzT0RVM05qZ3lNakl3SGhjTk1qWXdPREF6TVRNME16UXlXaGNOTXpZd056TXhNVE0wTXpReQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzT0RVM05qZ3lNakl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSSi9CejZSL2R2b0pHQ2tMLzAwL1UxZGY3VGJxNStwVTZVK0tLNjFTL3cKRjQwUlkwZmpHME1QWHZPM3RtZ0hOQ2hDTmI1Y1pCUW42dEtsanZpWndIVzlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUZualFkWHNiZllPU09MR3R5WCtKCm40a2poNlV3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQVByckNFVGdIVHlreWdidjJnUUNFQTlTYkU2VTVDL3oKSTNFNjh3MTVKa3NDSUFUMU5CWHBOU2lxRXhZdFp6UHhCc0FFbnJacmVBOFhTL2JLdU5yVVBLdHcKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdSdTR5TTE4VUN6U28zUE5YREJlSFZ4b1dySGNZYU5CbFVLbGcyTmxlVjlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQzhuVzcwc212Z3JWVUdZSFhpa1FLazhtY1dXVi9ZY0kxb2d0bDZaWEswNUlyZWU5SXdYQQpES216dEhwK1BtWUNobGJoTGpVNXBnaHN2UU5McFIwM3lRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
